import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <title>대단하지만 엄청나지는 않은 아윤이 소개 사이트</title>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
